# Generated by Django 2.2.3 on 2019-08-19 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Restorant')),
                ('expense', models.IntegerField(blank=True, default=0, null=True, verbose_name='expense')),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Work Type')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Ad Soyad')),
                ('starting_date', models.DateField(help_text='Başlangıç tarihinizi giriniz.', verbose_name='Başlangıç tarihi')),
                ('ending_date', models.DateField(help_text='Bitiş tarihinizi giriniz.', verbose_name='Bitiş tarihi')),
                ('expose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Price', verbose_name='restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı')),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.WorkType', verbose_name='work type')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='CurrentRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Bugünün Tarihi')),
                ('expose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Price', verbose_name='restaurant')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='Kullanıcı Adı')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.WorkType', verbose_name='work type')),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name_plural': 'Cari Yemek Hareketi',
                'verbose_name': 'Cari Yemek Hareketi',
            },
        ),
    ]
