# Generated by Django 2.2.3 on 2019-07-26 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('work_type', models.IntegerField(choices=[(1, 'Stajyer'), (2, 'Çalışan')], default=1, verbose_name='Alan Seçimi')),
                ('starting_date', models.DateField(help_text='Başlangıç tarihinizi giriniz.', verbose_name='Başlangıç tarihi')),
                ('ending_date', models.DateField(help_text='Bitiş tarihinizi giriniz.', verbose_name='Bitiş tarihi')),
                ('restaurant', models.IntegerField(choices=[(1, 'Ücret'), (2, 'Çınaraltı Restorant'), (3, 'Üniversite Yemekhanesi')], default=1, verbose_name='Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='CurrentRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(verbose_name='Bugünün Tarihi')),
                ('status', models.IntegerField(choices=[(1, 'Ücret'), (2, 'Çınaraltı Restorant'), (3, 'Üniversite Yemekhanesi')], default=1, verbose_name='Restaurant')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='Çalışan')),
            ],
            options={
                'verbose_name': 'Cari Yemek Hareketi',
                'ordering': ('-id',),
                'verbose_name_plural': 'Cari Yemek Hareketi',
            },
        ),
    ]
