# Generated by Django 2.2.3 on 2019-08-26 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentrestaurant',
            options={'ordering': ('-id',), 'verbose_name': 'Current Food Movement', 'verbose_name_plural': 'Current Food Movement'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('name',), 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'Work Type'},
        ),
        migrations.RemoveField(
            model_name='currentrestaurant',
            name='name',
        ),
        migrations.AddField(
            model_name='currentrestaurant',
            name='worktype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.WorkType', verbose_name='Work Type'),
        ),
        migrations.AlterField(
            model_name='currentrestaurant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date : yyyy-aa-gg', verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='currentrestaurant',
            name='expose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Price', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='currentrestaurant',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='price',
            name='expense',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Expense'),
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ending_date',
            field=models.DateField(help_text='Enter your ending date.Date : yyyy-aa-gg', verbose_name='Ending Date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Price', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name Surname'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='starting_date',
            field=models.DateField(help_text='Enter your starting date.Date : yyyy-aa-gg', verbose_name='Starting Date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.WorkType', verbose_name='Work Type'),
        ),
    ]
