# Generated by Django 2.2.3 on 2019-08-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190826_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='expense',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Expense'),
        ),
    ]
