# Generated by Django 2.2.3 on 2019-08-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190826_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='prices',
            field=models.ManyToManyField(blank=True, related_name='worktype_prices', to='accounts.Price', verbose_name='Prices Preferences'),
        ),
    ]
